Released episode: 0_zephyr_Math_Physics_and_other_Metaphors
Released episode: 0_zephyr_Math_Physics_and_other_Metaphors
Released episode: 0_zephyr_Math_Physics_and_other_Metaphors
Released episode: 0_zephyr_Math_Physics_and_other_Metaphors
Released episode: 0_zephyr_Math_Physics_and_other_Metaphors
Released episode: 0_zephyr_Math_Physics_and_other_Metaphors
Released episode: 0_zephyr_Math_Physics_and_other_Metaphors
Released episode: 0_zephyr_Math_Physics_and_other_Metaphors
Released episode: 0_zephyr_Math_Physics_and_other_Metaphors
Released episode: 0_zephyr_Math_Physics_and_other_Metaphors
Released episode: 0_zephyr_Math_Physics_and_other_Metaphors
Released episode: 0_zephyr_Math_Physics_and_other_Metaphors
Released episode: 0_zephyr_Math_Physics_and_other_Metaphors
Released episode: 0_zephyr_Math_Physics_and_other_Metaphors
Released episode: 0_zephyr_Math_Physics_and_other_Metaphors
Released episode: 0_zephyr_Math_Physics_and_other_Metaphors
Released episode: 0_zephyr_Math_Physics_and_other_Metaphors
Released episode: 0_zephyr_Math_Physics_and_other_Metaphors
Released episode: 0_zephyr_Math_Physics_and_other_Metaphors
Released episode: 0_zephyr_Math_Physics_and_other_Metaphors
Released episode: 0_zephyr_Math_Physics_and_other_Metaphors
Released episode: 0_zephyr_Math_Physics_and_other_Metaphors
Released episode: 0_zephyr_Math_Physics_and_other_Metaphors
Released episode: 0_zephyr_Math_Physics_and_other_Metaphors
Released episode: 0_zephyr_Math_Physics_and_other_Metaphors
Released episode: 0_zephyr_Math_Physics_and_other_Metaphors
Released episode: 0_starling_lm_Math_Physics_and_other_Metaphors
Released episode: 0_starling_lm_Math_Physics_and_other_Metaphors
Released episode: 0_zephyr_Math_Physics_and_other_Metaphors
Released episode: 0_starling_lm_Math_Physics_and_other_Metaphors
Released episode: 1_zephyr_Math_Physics_and_other_Metaphors
Released episode: 1_zephyr_Math_Physics_and_other_Metaphors
Released episode: 0_starling_lm_Math_Physics_and_other_Metaphors
Released episode: 1_zephyr_Math_Physics_and_other_Metaphors
Released episode: 0_starling_lm_Math_Physics_and_other_Metaphors
Released episode: 1_zephyr_Math_Physics_and_other_Metaphors
Released episode: 0_starling_lm_Math_Physics_and_other_Metaphors
Released episode: 0_starling_lm_Math_Physics_and_other_Metaphors
Released episode: 0_zephyr_Math_Physics_and_other_Metaphors
Released episode: 1_zephyr_Math_Physics_and_other_Metaphors
Released episode: 1_zephyr_Math_Physics_and_other_Metaphors
Released episode: 0_zephyr_Math_Physics_and_other_Metaphors
Released episode: 0_starling_lm_Math_Physics_and_other_Metaphors
Released episode: 1_zephyr_Math_Physics_and_other_Metaphors
Released episode: 0_starling_lm_Math_Physics_and_other_Metaphors
Released episode: 0_zephyr_Math_Physics_and_other_Metaphors
Released episode: 0_zephyr_Math_Physics_and_other_Metaphors
Released episode: 0_starling_lm_Math_Physics_and_other_Metaphors
Released episode: 0_starling_lm_Math_Physics_and_other_Metaphors
[38;5;255mAverage Time for zephyr to produce script: 716 seconds[0m
Released episode: 0_starling_lm_Math_Physics_and_other_Metaphors
Released episode: 0_zephyr_How_to_think_about_injectivity_in_math
[38;5;255mAverage Time for zephyr to produce script: 716 seconds[0m
[38;5;255mAverage Time for starling-lm to produce script: 389 seconds[0m
Released episode: 0_zephyr_Math_Physics_and_other_Metaphors
Released episode: 0_starling_lm_How_to_think_about_injectivity_in_math
Released episode: 0_starling_lm_How_to_think_about_injectivity_in_math
Released episode: 0_zephyr_How_to_think_about_injectivity_in_math
[38;5;255mAverage Time for zephyr to produce script: 716 seconds[0m
[38;5;255mAverage Time for starling-lm to produce script: 389 seconds[0m
[38;5;255mAverage Time for neural-chat to produce script: 461 seconds[0m
[38;5;255mAverage Time for zephyr to produce script: 716 seconds[0m
[38;5;255mAverage Time for starling-lm to produce script: 389 seconds[0m
[38;5;255mAverage Time for neural-chat to produce script: 461 seconds[0m
[38;5;255mAverage Time for llama2-uncensored to produce script: 147 seconds[0m
[38;5;255mAverage Time for zephyr to produce script: 716 seconds[0m
[38;5;255mAverage Time for starling-lm to produce script: 389 seconds[0m
[38;5;255mAverage Time for neural-chat to produce script: 461 seconds[0m
[38;5;255mAverage Time for llama2-uncensored to produce script: 147 seconds[0m
[38;5;255mAverage Time for openhermes to produce script: 196 seconds[0m
Released episode: 0_llama2_uncensored_How_to_think_about_injectivity_in_math
Released episode: 0_llama2_uncensored_How_to_think_about_injectivity_in_math
[38;5;255mAverage Time for zephyr to produce script: 716 seconds[0m
[38;5;255mAverage Time for starling-lm to produce script: 389 seconds[0m
[38;5;255mAverage Time for neural-chat to produce script: 461 seconds[0m
[38;5;255mAverage Time for llama2-uncensored to produce script: 147 seconds[0m
[38;5;255mAverage Time for openhermes to produce script: 196 seconds[0m
[38;5;255mAverage Time for orca2 to produce script: 166 seconds[0m
Released episode: 0_llama2_uncensored_How_to_think_about_injectivity_in_math
Released episode: 0_neural_chat_How_to_think_about_injectivity_in_math
Released episode: 0_llama2_uncensored_How_to_think_about_injectivity_in_math
Released episode: 0_llama2_uncensored_How_to_think_about_injectivity_in_math
Released episode: 0_llama2_uncensored_How_to_think_about_injectivity_in_math
[38;5;255mAverage Time for zephyr to produce script: 232 seconds[0m
Released episode: 0_zephyr_Boilerplate_coding
Released episode: 0_zephyr_Boilerplate_coding
Released episode: 0_zephyr_Boilerplate_coding
Released episode: 0_zephyr_Boilerplate_coding
Released episode: 0_zephyr_Boilerplate_coding
[38;5;255mAverage Time for zephyr to produce script: 186 seconds[0m
Released episode: 0_zephyr_Logic_in_Computer_Science
Released episode: 0_zephyr_Logic_in_Computer_Science
[38;5;255mAverage Time for zephyr to produce script: 186 seconds[0m
[38;5;255mAverage Time for starling-lm to produce script: 223 seconds[0m
Released episode: 0_starling_lm_Logic_in_Computer_Science
Released episode: 0_starling_lm_Logic_in_Computer_Science
Released episode: 0_zephyr_Logic_in_Computer_Science
[38;5;255mAverage Time for orca2 to produce script: 335 seconds[0m
Released episode: 0_orca2_Predicate_Logic
[38;5;255mAverage Time for orca2 to produce script: 317 seconds[0m
Released episode: 0_orca2_Natural_Deduction
Released episode: 0_orca2_Natural_Deduction
Released episode: 0_orca2_Predicate_Logic
Released episode: 0_orca2_Predicate_Logic
Released episode: 0_orca2_Natural_Deduction
Released episode: 0_orca2_Predicate_Logic
Released episode: 0_orca2_Natural_Deduction
Released episode: 0_orca2_Predicate_Logic
[38;5;255mAverage Time for orca2 to produce script: 131 seconds[0m
[38;5;255mAverage Time for orca2 to produce script: 125 seconds[0m
[38;5;255mAverage Time for orca2 to produce script: 144 seconds[0m
[38;5;255mAverage Time for orca2 to produce script: 151 seconds[0m
[38;5;255mAverage Time for orca2 to produce script: 152 seconds[0m
[38;5;255mAverage Time for orca2 to produce script: 156 seconds[0m
[38;5;255mAverage Time for orca2 to produce script: 156 seconds[0m
[38;5;255mAverage Time for orca2 to produce script: 154 seconds[0m
[38;5;255mAverage Time for orca2 to produce script: 160 seconds[0m
[38;5;255mAverage Time for orca2 to produce script: 158 seconds[0m
[38;5;255mAverage Time for orca2 to produce script: 159 seconds[0m
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 29, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 35, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 35, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 35, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 35, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 35, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Error in choose_episode_path: [WinError 183] Cannot create a file when that file already exists: './shared/StreamingAssets/unreleased_episodes/0_orca2_Advanced_Logic_Topics_Optional_'
Error in choose_episode_path: [WinError 183] Cannot create a file when that file already exists: './shared/StreamingAssets/unreleased_episodes/0_orca2_Advanced_Logic_Topics_Optional_'
Error in choose_episode_path: [WinError 183] Cannot create a file when that file already exists: './shared/StreamingAssets/unreleased_episodes/0_orca2_Advanced_Logic_Topics_Optional_'
Error in choose_episode_path: [WinError 183] Cannot create a file when that file already exists: './shared/StreamingAssets/unreleased_episodes/0_orca2_Advanced_Logic_Topics_Optional_'
Error in choose_episode_path: [WinError 183] Cannot create a file when that file already exists: './shared/StreamingAssets/unreleased_episodes/0_orca2_Advanced_Logic_Topics_Optional_'
Error in choose_episode_path: [WinError 183] Cannot create a file when that file already exists: './shared/StreamingAssets/unreleased_episodes/0_orca2_Advanced_Logic_Topics_Optional_'
Error in choose_episode_path: module 'os' has no attribute 'exists'
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 35, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 35, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 35, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 35, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 35, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 35, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 35, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 35, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 35, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 35, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 35, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 35, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 35, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 35, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 35, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 35, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 35, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 35, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 35, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 35, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 35, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "/home/steffen/.local/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/steffen/.local/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/steffen/.local/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/steffen/.local/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/steffen/livestream_script_generator/./restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "/usr/lib/python3.10/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/lib/python3.10/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "/home/steffen/.local/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/steffen/.local/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/steffen/.local/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/steffen/.local/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/steffen/livestream_script_generator/./restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "/usr/lib/python3.10/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/lib/python3.10/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "/home/steffen/.local/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/steffen/.local/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/steffen/.local/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/steffen/.local/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/steffen/livestream_script_generator/./restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "/usr/lib/python3.10/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/lib/python3.10/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "/home/steffen/.local/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/steffen/.local/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/steffen/.local/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/steffen/.local/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/steffen/livestream_script_generator/./restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "/usr/lib/python3.10/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/lib/python3.10/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "/home/steffen/.local/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/steffen/.local/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/steffen/.local/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/steffen/.local/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/steffen/livestream_script_generator/./restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "/usr/lib/python3.10/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/lib/python3.10/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "/home/steffen/.local/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/steffen/.local/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/steffen/.local/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/steffen/.local/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/steffen/livestream_script_generator/./restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "/usr/lib/python3.10/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/lib/python3.10/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SyncthingServiceAcct\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SyncthingServiceAcct\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SyncthingServiceAcct\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SyncthingServiceAcct\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SyncthingServiceAcct\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SyncthingServiceAcct\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SyncthingServiceAcct\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SyncthingServiceAcct\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SyncthingServiceAcct\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SyncthingServiceAcct\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SyncthingServiceAcct\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SyncthingServiceAcct\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SyncthingServiceAcct\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SyncthingServiceAcct\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SyncthingServiceAcct\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SyncthingServiceAcct\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SyncthingServiceAcct\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SyncthingServiceAcct\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SyncthingServiceAcct\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SyncthingServiceAcct\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SyncthingServiceAcct\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SyncthingServiceAcct\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SyncthingServiceAcct\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SyncthingServiceAcct\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SyncthingServiceAcct\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SyncthingServiceAcct\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\steffen\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(supported_scenes, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SupportedScenes is not JSON serializable
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 37, in set_supported_scenes
    json.dump(data, "./shared/supported_scenes.json")
  File "C:\Users\Steffen\anaconda3\Lib\json\__init__.py", line 180, in dump
    fp.write(chunk)
    ^^^^^^^^
AttributeError: 'str' object has no attribute 'write'
Error in choose_episode_path: cannot access local variable 'released_path' where it is not associated with a value
Error in choose_episode_path: cannot access local variable 'released_path' where it is not associated with a value
Error in choose_episode_path: cannot access local variable 'released_path' where it is not associated with a value
Error in choose_episode_path: cannot access local variable 'released_path' where it is not associated with a value
Error in choose_episode_path: cannot access local variable 'released_path' where it is not associated with a value
Error in choose_episode_path: cannot access local variable 'released_path' where it is not associated with a value
Error in choose_episode_path: cannot access local variable 'released_path' where it is not associated with a value
Error in choose_episode_path: cannot access local variable 'released_path' where it is not associated with a value
Error in choose_episode_path: cannot access local variable 'released_path' where it is not associated with a value
Error in choose_episode_path: cannot access local variable 'released_path' where it is not associated with a value
Error in choose_episode_path: cannot access local variable 'released_path' where it is not associated with a value
Error in choose_episode_path: Destination path './shared/StreamingAssets/released_episodes/0_llama2_uncensored_RasperryPi_Pico\0_llama2_uncensored_RasperryPi_Pico' already exists
Error in choose_episode_path: Destination path './shared/StreamingAssets/released_episodes/0_openhermes_RasperryPi_Pico\0_openhermes_RasperryPi_Pico' already exists
Error in choose_episode_path: Destination path './shared/StreamingAssets/released_episodes/0_llama2_uncensored_RasperryPi_Pico\0_llama2_uncensored_RasperryPi_Pico' already exists
Error in choose_episode_path: cannot access local variable 'released_path' where it is not associated with a value
Error in choose_episode_path: cannot access local variable 'released_path' where it is not associated with a value
Error in choose_episode_path: cannot access local variable 'released_path' where it is not associated with a value
Error in choose_episode_path: cannot access local variable 'released_path' where it is not associated with a value
Error in choose_episode_path: cannot access local variable 'released_path' where it is not associated with a value
Error in choose_episode_path: cannot access local variable 'released_path' where it is not associated with a value
Error in choose_episode_path: cannot access local variable 'released_path' where it is not associated with a value
Error in choose_episode_path: cannot access local variable 'released_path' where it is not associated with a value
Error in choose_episode_path: cannot access local variable 'released_path' where it is not associated with a value
Error in choose_episode_path: cannot access local variable 'released_path' where it is not associated with a value
Error in choose_episode_path: cannot access local variable 'released_path' where it is not associated with a value
Error in choose_episode_path: cannot access local variable 'released_path' where it is not associated with a value
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 38, in set_supported_scenes
    file.write(supported_scenes.to_json())
TypeError: write() argument must be str, not dict
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 38, in set_supported_scenes
    file.write(supported_scenes.to_json())
TypeError: write() argument must be str, not dict
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 38, in set_supported_scenes
    file.write(supported_scenes.to_json())
TypeError: write() argument must be str, not dict
Exception on /setSupportedScenes [PUT]
Traceback (most recent call last):
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\anaconda3\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Steffen\OneDrive\Projekte\livestream_script_generator\restApi.py", line 38, in set_supported_scenes
    file.write(supported_scenes.to_json())
TypeError: write() argument must be str, not dict
